meta:
  import_trasks_from: features.yaml

tasks:
- source: scripts/get.py
  product:
    nb: products/{{out}}/get.ipynb
    data: products/{{out}}/get.csv

- source: scripts/fit.py
  product:
    nb: products/{{out}}/fit.ipynb
    model: products/{{out}}/model.pickle
