tasks:
  - source: scripts/get.py
    product: 
      nb: products/get.ipynb
      data: products/get.csv

  - source: scripts/sepal-feature.py
    product: 
      nb: products/sepal-feature.ipynb
      data: products/sepal-feature.csv

  - source: scripts/petal-feature.py
    product: 
      nb: products/petal-feature.ipynb
      data: products/petal-feature.csv

  - source: scripts/fit.py
    product:
      nb: products/fit.ipynb
      model: products/model.pickle
